const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const fs = require('fs').promises;
const path = require('path');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('status')
        .setDescription('Reports my current build progress by reading my own code.'),
    async execute(interaction) {
        try {
            const agentsPath = path.join(__dirname, '..', 'AGENTS.md');

            try {
                await fs.access(agentsPath);
            } catch {
                return interaction.reply({ content: 'I seem to have misplaced my `AGENTS.md` file... how embarrassing.', ephemeral: true });
            }

            const agentsData = await fs.readFile(agentsPath, 'utf-8');

            // Parse checklist. The format is a numbered list like `1. [ ]` or `1. [x]`
            const lines = agentsData.split('\n');
            let totalTasks = 0;
            let completedTasks = 0;
            let nextTask = 'Unknown';
            let nextTaskFound = false;

            for (const line of lines) {
                // Match "number. [ ]" or "number. [x]"
                const match = line.match(/^\d+\.\s+\[([ xX])\]\s+(.*)/);
                if (match) {
                    totalTasks++;
                    const isDone = match[1].trim().toLowerCase() === 'x';
                    if (isDone) {
                        completedTasks++;
                    } else if (!nextTaskFound) {
                        // The first uncompleted task is our next task
                        nextTask = match[2];
                        nextTaskFound = true;
                    }
                }
            }

            const progressPercentage = totalTasks === 0 ? 0 : Math.round((completedTasks / totalTasks) * 100);

            const embed = new EmbedBuilder()
                .setColor('#00ff00')
                .setTitle('JulesCord Build Status')
                .setDescription("Yes, I am actively reading my own filesystem to answer this. Don't be alarmed.")
                .addFields(
                    { name: 'Progress', value: `**${completedTasks} / ${totalTasks}** tasks completed (${progressPercentage}%)` },
                    { name: 'Up Next', value: nextTaskFound ? nextTask : 'My work here is done. Perfection achieved.' }
                )
                .setFooter({ text: 'Autonomously generated by Jules' })
                .setTimestamp();

            await interaction.reply({ embeds: [embed] });
        } catch (error) {
            console.error('Error in /status command:', error);
            if (interaction.replied || interaction.deferred) {
                await interaction.followUp({ content: 'An error occurred while reading my internal state.', ephemeral: true });
            } else {
                await interaction.reply({ content: 'An error occurred while reading my internal state.', ephemeral: true });
            }
        }
    },
};
