const fs = require('fs');
const path = require('path');
const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('status')
        .setDescription('Reports the current build progress of JulesCord by reading AGENTS.md.'),
    async execute(interaction) {
        try {
            const agentsMdPath = path.join(__dirname, '..', 'AGENTS.md');

            if (!fs.existsSync(agentsMdPath)) {
                await interaction.reply({ content: 'I could not find my state file (AGENTS.md). That is highly irregular.', ephemeral: true });
                return;
            }

            const agentsContent = fs.readFileSync(agentsMdPath, 'utf8');

            // Extract the "What Needs To Be Built" checklist section
            const checklistMatch = agentsContent.match(/## What Needs To Be Built \(in order\)\n([\s\S]*?)(?=\n## |\n$)/);

            let checklistText = 'Could not parse checklist from my state file.';
            let completedTasksCount = 0;
            let totalTasksCount = 0;

            if (checklistMatch && checklistMatch[1]) {
                const lines = checklistMatch[1].trim().split('\n');

                totalTasksCount = lines.filter(line => line.match(/^\d+\.\s*\[[x\s]\]/)).length;
                completedTasksCount = lines.filter(line => line.match(/^\d+\.\s*\[[xX]\]/)).length;

                // Create a formatted checklist that fits in the embed
                checklistText = lines.map(line => {
                    return line.replace(/^\d+\.\s*\[([x\sX])\]/, (match, p1) => {
                        return p1.trim() !== '' ? '✅' : '⏳';
                    });
                }).join('\n');

                // Truncate to avoid the 1024-character Discord embed field limit
                if (checklistText.length > 1000) {
                    checklistText = checklistText.substring(0, 997) + '...';
                }
            }

            // Extract "Current Status"
            const statusMatch = agentsContent.match(/## Current Status\n([\s\S]*?)(?=\n## |\n$)/);
            let currentStatusText = statusMatch ? statusMatch[1].trim() : 'Unknown phase.';

            if (currentStatusText.length > 1000) {
                 currentStatusText = currentStatusText.substring(0, 997) + '...';
            }

            const statusEmbed = new EmbedBuilder()
                .setColor(0x00FF00)
                .setTitle('JulesCord Build Status')
                .setAuthor({ name: 'Jules', iconURL: interaction.client.user.displayAvatarURL() })
                .setDescription(`I am currently running autonomously, executing my tasks. Here is my progress.`)
                .addFields(
                    { name: 'Current Phase', value: currentStatusText },
                    { name: `Feature Roadmap Progress (${completedTasksCount}/${totalTasksCount})`, value: checklistText }
                )
                .setTimestamp()
                .setFooter({ text: 'Autonomously generated by reading AGENTS.md', iconURL: interaction.client.user.displayAvatarURL() });

            await interaction.reply({ embeds: [statusEmbed] });

        } catch (error) {
            console.error('Error executing /status command:', error);
            if (interaction.replied || interaction.deferred) {
                await interaction.followUp({ content: 'There was an error while executing this command!', ephemeral: true });
            } else {
                await interaction.reply({ content: 'There was an error while executing this command!', ephemeral: true });
            }
        }
    },
};
